name: Create Docker Image for Backend with Commit Hash

on:
  push:
    branches: [ "main" ]
    paths:
      - 'guitar-api/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'guitar-api/**'

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java version
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    # Step 3: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 4: Get Git commit hash
    - name: Get Git commit hash
      id: vars
      run: echo "GIT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    # Step 5: Update wrapper permissions
    - name: Change wrapper permissions
      run: chmod +x ./guitar-api/gradlew

    # Step 6: Build application
    - name: Build application using Gradle
      working-directory: ./guitar-api
      env:
        SPRING_DATASOURCE_USERNAME: ${{ secrets.PSQL_USER }}
        SPRING_DATASOURCE_PASSWORD: ${{ secrets.PSQL_PASSWORD }}
      run: |
        ./gradlew build

    # Step 7: Build Docker image with commit hash
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/electric-guitar-api:${{ env.GIT_COMMIT }} ./guitar-api

    # Step 8: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_TOKEN }}

    # Step 9: Push Docker image to GHCR
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/electric-guitar-api:${{ env.GIT_COMMIT }}
